# Generated by Django 4.0.4 on 2022-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0006_alter_customuser_address_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.CharField(default='{}', max_length=5000),
        ),
    ]
