# Generated by Django 4.0.4 on 2022-05-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0007_customuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart',
        ),
    ]
