# Generated by Django 4.0.4 on 2022-05-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0009_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customuser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
