# Generated by Django 4.0.4 on 2022-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0010_rename_customuser_cart_user_alter_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customuser',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
