# Generated by Django 4.0.4 on 2022-05-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0013_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripe',
            name='customername',
        ),
    ]
