# Generated by Django 4.0.4 on 2022-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eweb', '0014_remove_stripe_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe',
            name='customerid',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
